/**
 * ========================================
 * 📄 Professional PDF Reports - تقارير PDF احترافية
 * ========================================
 * 
 * توليد تقارير PDF احترافية متنوعة
 * دعم الشعار والعناوين المخصصة
 * 
 * الإصدار 1.0
 */

// ===== Namespace to avoid conflicts =====
window.NFReports = (function() {
    'use strict';
    
    // ===== Default Config =====
    const DEFAULT_CONFIG = {
        companyName: 'نظام تقييم المركبات المستردة',
        companyNameEn: 'Repossessed Vehicle Evaluation System',
        logo: null, // Base64 or URL
        primaryColor: '#1a5f7a',
        secondaryColor: '#667eea',
        footerText: 'تم إنشاء التقرير بواسطة نظام تقييم المركبات',
        footerTextEn: 'Generated by Vehicle Evaluation System'
    };
    
    let config = { ...DEFAULT_CONFIG };
    
    // ===== Set Config =====
    function setConfig(newConfig) {
        config = { ...config, ...newConfig };
    }
    
    // ===== Get jsPDF =====
    function getJsPDF() {
        if (typeof jspdf !== 'undefined') return jspdf.jsPDF;
        if (typeof window.jspdf !== 'undefined') return window.jspdf.jsPDF;
        throw new Error('jsPDF library not loaded');
    }
    
    // ===== Common PDF Setup =====
    function setupPDF(orientation = 'p') {
        const jsPDF = getJsPDF();
        const pdf = new jsPDF(orientation, 'mm', 'a4');
        return pdf;
    }
    
    // ===== Add Header =====
    function addHeader(pdf, title, subtitle = '') {
        const pageWidth = pdf.internal.pageSize.getWidth();
        
        // Header background
        pdf.setFillColor(26, 95, 122);
        pdf.rect(0, 0, pageWidth, 35, 'F');
        
        // Gradient effect
        pdf.setFillColor(102, 126, 234);
        pdf.rect(0, 30, pageWidth, 5, 'F');
        
        // Title
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(18);
        pdf.setFont('helvetica', 'bold');
        pdf.text(title, pageWidth / 2, 15, { align: 'center' });
        
        // Subtitle
        if (subtitle) {
            pdf.setFontSize(12);
            pdf.setFont('helvetica', 'normal');
            pdf.text(subtitle, pageWidth / 2, 25, { align: 'center' });
        }
        
        // Date
        pdf.setFontSize(10);
        pdf.text(`Date: ${new Date().toLocaleDateString('en-US')}`, pageWidth - 15, 25, { align: 'right' });
        
        pdf.setTextColor(0, 0, 0);
        return 45; // Return Y position after header
    }
    
    // ===== Add Footer =====
    function addFooter(pdf) {
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const totalPages = pdf.internal.getNumberOfPages();
        
        for (let i = 1; i <= totalPages; i++) {
            pdf.setPage(i);
            
            // Footer line
            pdf.setDrawColor(200, 200, 200);
            pdf.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);
            
            // Footer text
            pdf.setFontSize(8);
            pdf.setTextColor(128, 128, 128);
            pdf.text(config.footerTextEn, 15, pageHeight - 8);
            pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 15, pageHeight - 8, { align: 'right' });
        }
    }
    
    // ===== Add Section =====
    function addSection(pdf, title, y) {
        const pageWidth = pdf.internal.pageSize.getWidth();
        
        pdf.setFillColor(26, 95, 122);
        pdf.rect(15, y - 5, pageWidth - 30, 8, 'F');
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.text(title, 18, y);
        pdf.setTextColor(0, 0, 0);
        
        return y + 12;
    }
    
    // ===== Add Row =====
    function addRow(pdf, label, value, y, labelWidth = 55) {
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text(label + ':', 18, y);
        pdf.setFont('helvetica', 'normal');
        pdf.text(String(value || 'N/A'), 18 + labelWidth, y);
        return y + 6;
    }
    
    // ===== Check Page Break =====
    function checkPageBreak(pdf, y, margin = 30) {
        const pageHeight = pdf.internal.pageSize.getHeight();
        if (y > pageHeight - margin) {
            pdf.addPage();
            return 20;
        }
        return y;
    }
    
    // ===== Generate Comprehensive Inventory Report =====
    async function generateInventoryReport(vehicles, title = 'COMPREHENSIVE INVENTORY REPORT') {
        const pdf = setupPDF('p');
        let y = addHeader(pdf, title, `Total Vehicles: ${vehicles.length}`);
        
        // Summary section
        y = addSection(pdf, 'SUMMARY', y);
        
        const totalValue = vehicles.reduce((sum, v) => sum + (parseFloat(v.marketValue) || 0), 0);
        const avgValue = vehicles.length > 0 ? totalValue / vehicles.length : 0;
        
        // Count by rating
        const ratings = { excellent: 0, good: 0, fair: 0, poor: 0 };
        vehicles.forEach(v => {
            if (v.overallRating && ratings[v.overallRating] !== undefined) {
                ratings[v.overallRating]++;
            }
        });
        
        y = addRow(pdf, 'Total Vehicles', vehicles.length, y);
        y = addRow(pdf, 'Total Value', `${totalValue.toLocaleString()} SAR`, y);
        y = addRow(pdf, 'Average Value', `${avgValue.toLocaleString()} SAR`, y);
        y = addRow(pdf, 'Excellent Condition', ratings.excellent, y);
        y = addRow(pdf, 'Good Condition', ratings.good, y);
        y = addRow(pdf, 'Fair Condition', ratings.fair, y);
        y = addRow(pdf, 'Poor Condition', ratings.poor, y);
        
        y += 10;
        
        // Vehicles table
        y = addSection(pdf, 'VEHICLES LIST', y);
        y += 5;
        
        // Table header
        pdf.setFillColor(240, 240, 240);
        pdf.rect(15, y - 4, 180, 8, 'F');
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text('#', 18, y);
        pdf.text('Vehicle', 30, y);
        pdf.text('VIN', 80, y);
        pdf.text('Plate', 120, y);
        pdf.text('Value', 145, y);
        pdf.text('Rating', 170, y);
        y += 8;
        
        // Table rows
        pdf.setFont('helvetica', 'normal');
        vehicles.forEach((vehicle, index) => {
            y = checkPageBreak(pdf, y);
            
            if (index % 2 === 0) {
                pdf.setFillColor(250, 250, 250);
                pdf.rect(15, y - 4, 180, 6, 'F');
            }
            
            pdf.text(String(index + 1), 18, y);
            pdf.text(`${vehicle.make || ''} ${vehicle.model || ''} ${vehicle.year || ''}`.substring(0, 25), 30, y);
            pdf.text((vehicle.vin || 'N/A').substring(0, 18), 80, y);
            pdf.text((vehicle.plateNo || 'N/A').substring(0, 12), 120, y);
            pdf.text(vehicle.marketValue ? `${parseFloat(vehicle.marketValue).toLocaleString()}` : 'N/A', 145, y);
            pdf.text(vehicle.overallRating || 'N/A', 170, y);
            y += 6;
        });
        
        addFooter(pdf);
        return pdf;
    }
    
    // ===== Generate Vehicle Detail Report =====
    async function generateVehicleDetailReport(vehicle) {
        const pdf = setupPDF('p');
        let y = addHeader(pdf, 'VEHICLE EVALUATION REPORT', `${vehicle.make} ${vehicle.model} ${vehicle.year}`);
        
        // Basic Information
        y = addSection(pdf, 'BASIC INFORMATION', y);
        y = addRow(pdf, 'Contract Number', vehicle.contractNo, y);
        y = addRow(pdf, 'Customer Name', vehicle.customerName, y);
        y = addRow(pdf, 'Make', vehicle.make, y);
        y = addRow(pdf, 'Model', vehicle.model, y);
        y = addRow(pdf, 'Year', vehicle.year, y);
        y = addRow(pdf, 'VIN', vehicle.vin, y);
        y = addRow(pdf, 'Plate Number', vehicle.plateNo, y);
        y = addRow(pdf, 'Odometer', vehicle.odometer ? `${vehicle.odometer} km` : 'N/A', y);
        y = addRow(pdf, 'Color', vehicle.color, y);
        y = addRow(pdf, 'Fuel Type', vehicle.fuelType, y);
        
        y += 5;
        
        // Valuation
        y = addSection(pdf, 'VALUATION & ASSESSMENT', y);
        y = addRow(pdf, 'Market Value', vehicle.marketValue ? `${parseFloat(vehicle.marketValue).toLocaleString()} SAR` : 'N/A', y);
        y = addRow(pdf, 'Overall Rating', vehicle.overallRating, y);
        y = addRow(pdf, 'Recommendation', vehicle.recommendation, y);
        
        y += 5;
        
        // Location Info
        if (vehicle.warehouseId || vehicle.recoveryLocation) {
            y = addSection(pdf, 'LOCATION INFORMATION', y);
            y = addRow(pdf, 'Current Location', vehicle.warehouseName || 'Not Assigned', y);
            y = addRow(pdf, 'Recovery Date', vehicle.recoveryDate, y);
            y = addRow(pdf, 'Recovery Location', vehicle.recoveryLocation, y);
        }
        
        y += 5;
        
        // Notes
        if (vehicle.notes) {
            y = addSection(pdf, 'NOTES', y);
            pdf.setFontSize(10);
            const splitNotes = pdf.splitTextToSize(vehicle.notes, 170);
            pdf.text(splitNotes, 18, y);
        }
        
        addFooter(pdf);
        return pdf;
    }
    
    // ===== Generate Warehouse Report =====
    async function generateWarehouseReport(warehouseId = 'all') {
        const warehouses = window.NFWarehouse ? NFWarehouse.getWarehouses() : [];
        let vehicles = [];
        if (typeof getVehicles === 'function') {
            vehicles = getVehicles();
        }
        
        const pdf = setupPDF('l'); // Landscape
        let y = addHeader(pdf, 'WAREHOUSE INVENTORY REPORT', warehouseId === 'all' ? 'All Locations' : warehouses.find(w => w.id === warehouseId)?.name || warehouseId);
        
        // Summary by warehouse
        y = addSection(pdf, 'SUMMARY BY LOCATION', y);
        
        const counts = window.NFWarehouse ? NFWarehouse.countVehiclesByWarehouse(vehicles) : {};
        
        // Table header
        pdf.setFillColor(240, 240, 240);
        pdf.rect(15, y - 4, 260, 8, 'F');
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Location', 18, y);
        pdf.text('Code', 80, y);
        pdf.text('Vehicles', 120, y);
        pdf.text('Total Value', 160, y);
        pdf.text('Manager', 220, y);
        y += 8;
        
        // Table rows
        pdf.setFont('helvetica', 'normal');
        Object.values(counts).forEach((item, index) => {
            y = checkPageBreak(pdf, y);
            
            if (index % 2 === 0) {
                pdf.setFillColor(250, 250, 250);
                pdf.rect(15, y - 4, 260, 6, 'F');
            }
            
            pdf.text(item.warehouse.name || 'Unknown', 18, y);
            pdf.text(item.warehouse.code || '-', 80, y);
            pdf.text(String(item.count), 120, y);
            pdf.text(`${item.totalValue.toLocaleString()} SAR`, 160, y);
            pdf.text(item.warehouse.manager || '-', 220, y);
            y += 6;
        });
        
        addFooter(pdf);
        return pdf;
    }
    
    // ===== Generate Discrepancy Report =====
    async function generateDiscrepancyReport(comparison, campaign1Name, campaign2Name) {
        const pdf = setupPDF('p');
        let y = addHeader(pdf, 'INVENTORY DISCREPANCY REPORT', `Comparing: ${campaign1Name} vs ${campaign2Name}`);
        
        // Summary
        y = addSection(pdf, 'DISCREPANCY SUMMARY', y);
        y = addRow(pdf, 'Newly Found', comparison.newlyFound?.length || 0, y);
        y = addRow(pdf, 'Now Missing', comparison.nowMissing?.length || 0, y);
        y = addRow(pdf, 'Status Changed', comparison.statusChanged?.length || 0, y);
        y = addRow(pdf, 'Unchanged', comparison.unchanged?.length || 0, y);
        
        y += 10;
        
        // Missing vehicles
        if (comparison.nowMissing?.length > 0) {
            y = addSection(pdf, 'MISSING VEHICLES', y);
            comparison.nowMissing.forEach(vehicleId => {
                y = checkPageBreak(pdf, y);
                pdf.text(`• ${vehicleId}`, 18, y);
                y += 5;
            });
            y += 5;
        }
        
        // Status changes
        if (comparison.statusChanged?.length > 0) {
            y = addSection(pdf, 'STATUS CHANGES', y);
            comparison.statusChanged.forEach(change => {
                y = checkPageBreak(pdf, y);
                pdf.text(`• ${change.vehicleId}: ${change.from} → ${change.to}`, 18, y);
                y += 5;
            });
        }
        
        addFooter(pdf);
        return pdf;
    }
    
    // ===== Generate Customer Report =====
    async function generateCustomerReport(customerName, vehicles) {
        const customerVehicles = vehicles.filter(v => v.customerName === customerName);
        
        const pdf = setupPDF('p');
        let y = addHeader(pdf, 'CUSTOMER VEHICLES REPORT', customerName);
        
        // Summary
        y = addSection(pdf, 'SUMMARY', y);
        const totalValue = customerVehicles.reduce((sum, v) => sum + (parseFloat(v.marketValue) || 0), 0);
        y = addRow(pdf, 'Total Vehicles', customerVehicles.length, y);
        y = addRow(pdf, 'Total Value', `${totalValue.toLocaleString()} SAR`, y);
        
        y += 10;
        
        // Vehicles list
        y = addSection(pdf, 'VEHICLES', y);
        
        customerVehicles.forEach((vehicle, index) => {
            y = checkPageBreak(pdf, y);
            
            pdf.setFontSize(11);
            pdf.setFont('helvetica', 'bold');
            pdf.text(`${index + 1}. ${vehicle.make} ${vehicle.model} ${vehicle.year}`, 18, y);
            y += 6;
            
            pdf.setFontSize(9);
            pdf.setFont('helvetica', 'normal');
            pdf.text(`VIN: ${vehicle.vin || 'N/A'} | Plate: ${vehicle.plateNo || 'N/A'} | Value: ${vehicle.marketValue ? parseFloat(vehicle.marketValue).toLocaleString() + ' SAR' : 'N/A'}`, 22, y);
            y += 8;
        });
        
        addFooter(pdf);
        return pdf;
    }
    
    // ===== Download PDF =====
    function downloadPDF(pdf, filename) {
        pdf.save(filename);
        
        if (window.NFNotify) {
            NFNotify.show({ message: 'تم تحميل التقرير بنجاح', type: 'success' });
        }
    }
    
    // ===== Quick Export Functions =====
    async function exportInventoryReport(vehicles) {
        const pdf = await generateInventoryReport(vehicles);
        downloadPDF(pdf, `Inventory_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    }
    
    async function exportVehicleReport(vehicle) {
        const pdf = await generateVehicleDetailReport(vehicle);
        downloadPDF(pdf, `Vehicle_Report_${vehicle.vin || vehicle.id}_${new Date().toISOString().split('T')[0]}.pdf`);
    }
    
    async function exportWarehouseReport(warehouseId) {
        const pdf = await generateWarehouseReport(warehouseId);
        downloadPDF(pdf, `Warehouse_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    }
    
    // ===== Return Public API =====
    return {
        setConfig,
        setupPDF,
        addHeader,
        addFooter,
        addSection,
        addRow,
        checkPageBreak,
        generateInventoryReport,
        generateVehicleDetailReport,
        generateWarehouseReport,
        generateDiscrepancyReport,
        generateCustomerReport,
        downloadPDF,
        exportInventoryReport,
        exportVehicleReport,
        exportWarehouseReport
    };
})();
